### PR TITLE
chore(ci): migrate to code climate

### PR DESCRIPTION
**Pull request by hongaar**
Code climate can show inline code coverage in pull requests (through browser plugins) and report on overall coverage diff in a PR, as well as report on a coverage threshold for changed code (defaults to 50%).

Pro: also runs static analysis on the code and reports on that.
Con: no standalone interface for code coverage analysis (needs browser plugin).

Depends on #24

### CODE REVIEW

**Review by AdrieanKhisbe — COMMENTED** [review]
Not sûre about it yet.

One thing though before we land #24,
It would be best @hongaar if you make an interactive rebase to remove thé commits And avoid the reverts

**Comment by hongaar** [comment]
> It would be best @hongaar if you make an interactive rebase to remove thé commits And avoid the reverts

I like squash merge commits ;)

**Comment by AdrieanKhisbe** [comment]
> > It would be best @hongaar if you make an interactive rebase to remove thé commits And avoid the reverts
> 
> I like squash merge commits ;)

Still, you cant clean your branch first (interactive rebase and push force on branch),
and then you squash &merge the few commits that remains.

IMO that far easier to review :)

**Comment by Ore4444** [comment]
@hongaar https://github.com/k88hudson/git-flight-rules#i-rebased-but-i-dont-want-to-force-push

**Comment by hongaar** [comment]
Not too important right now, closing in favour of more pressing issues.

**Pull request closed without merging**
