### PR TITLE
chore: update issue templates

### PR DESCRIPTION
**Pull request by hongaar**
Probably a bit preliminary to have these at this stage... but hey, it's free!

### CODE REVIEW

**Review by AdrieanKhisbe — CHANGES_REQUESTED** [review]
Interesting idea!
Though I would rather use sections `## blabla` to outline Issue description

**Comment by slinkardbrandon** [comment]
I like it

**Review by slinkardbrandon — APPROVED** [review]

**Review by AdrieanKhisbe — APPROVED** [review]
Good for me.
We'll improve them on the go :)

**Comment by AdrieanKhisbe** [comment]
(should be squash 😉 )

**Comment by hongaar** [comment]
> (should be squash 😉 )

@AdrieanKhisbe I think we can set the default somewhere in settings. Should we just set squash as default and disallow merge (in favour of rebase)?

**Comment by AdrieanKhisbe** [comment]
@hongaar This can be disabled indeed. 
If we were to disallow merge, I'll rather set rebase in default

**Comment by hongaar** [comment]
I don't think actually we can set a default, just disable some options...

image

**Pull request merged**
