### PR TITLE
chore: add probot-auto-merge configuration

### PR DESCRIPTION
**Pull request by hongaar**
Adds https://github.com/bobvanderlinden/probot-auto-merge

### CODE REVIEW

**Review by AdrieanKhisbe — CHANGES_REQUESTED** [review]
I really don't see the point.
Really

**Comment by hongaar** [comment]
Who doesn't like bots? 😉 🤖 

This is mainly about automation:
- adds some convenience (A opens PR -> B reviews -> A is 💤 -> bots never sleep)
- makes sure all PRs are merged the same way

**Comment by AdrieanKhisbe** [comment]
> Who doesn't like bots?
I do, but not all time, and everywhere.

When I open a PR, I want someone to be in control of the merge. (either me (maybe A), or the maintaner(maybe B))
No a bot, even more when the CD comes in and autopublish something...

> makes sure all PRs are merged the same way
🤔  ?

**Comment by hongaar** [comment]
> When I open a PR, I want someone to be in control of the merge. (either me (maybe A), or the maintaner(maybe B))

Just being curious, what aspect of the merge do you want to have control over?

> No a bot, even more when the CD comes in and autopublish something...

I wanted to say that for commits to master I would agree to do it manually, but actually now that I think about it, it might actually be a nice opportunity to do this with (automatically merged) PR's as well. So that each time we want to cut a new release, we'd need to open a PR for `master` <- `develop` and once it gets enough approvals, the bots will take over and merge and publish. Why not?

> makes sure all PRs are merged the same way

What I mean by this is, they will all use the same merge method and merge commit format.

---

My experience is that these kind of bots make it easier to work together on a project because the way code is propagated is very predictable.

Of course it takes away part of the fun of having some control over the process. But now we can have fun in having control over a process which has control over the other processes.... 😄

**Comment by AdrieanKhisbe** [comment]
> Just being curious, what aspect of the merge do you want to have control over?
Timing (+ squash over merge)

> I wanted to say that for commits to master I would agree to do it manually, but actually now that I think about it, it might actually be a nice opportunity to do this with (automatically merged) PR's as well. So that each time we want to cut a new release, we'd need to open a PR for `master` <- `develop` and once it gets enough approvals, the bots will take over and merge and publish. Why not?

And how do we have a _every requested review is due_? :wink:
Which we might want to need for some Pull request.
And it's not everyday we make a _MEP_ (_Mise en Production_: put to prod)

> What I mean by this is, they will all use the same merge method and merge commit format.

Isnt github PR interface enough? (with the extra flexibility as a bonux?)

----

:see_no_evil: Also would have been best if you bring that you were a contributor to [https://github.com/bobvanderlinden/probot-auto-merge/graphs/contributors](probot-auto-merge) :stuck_out_tongue_winking_eye:

**Comment by hongaar** [comment]
> 🙈 Also would have been best if you bring that you were a contributor

Crossed my mind to mention it but I don't see how it would change anything (it only costs money to keep this thing running).

Anyway, this is a proposal and I won't feel offended if this ends up getting closed without being merged. Let's wait for others to make a decision on this.

**Comment by Ore4444** [comment]
I think these kinds of bots are really useful to automate the parts of the collaboration we repeatedly do manually. I'd wait with these kinds of automations until after we get tired from doing process manually

**Pull request closed without merging**
