### PR TITLE
chore: publish as vorpal-reforged

### PR DESCRIPTION
**Pull request by hongaar**
The general consensus on Slack is to redistribute as `vorpal-reforged` ⚔️ 

We can track progress on this PR.

I kicked off by making some trivial changes to the readme. Probably not complete, feel free to add commits to my branch.

Also, I realise that refactoring/typing is not yet complete, but I think publishing as alpha/beta/rc now can help us getting some traction and speed up further development (if only so we can use it in our pet/production projects).

## Before initial release
- [x] Badges
- [ ] Decide on npm version/dist-tag
- [ ] Publish 🚀 

## Maybe also
- [ ] Further modify README
- [ ] Switch from Travis to GH Actions
- [ ] Use [semantic-release](https://github.com/semantic-release/semantic-release)
- [ ] Rename repo to vorpal-reforged (?)
- [ ] Move wiki to vorpaljs-reforged/vorpal
- [ ] Modify gh-pages branch and publish with GitHub
- [ ] Clean-up branches

### CODE REVIEW

**Comment by hongaar** [comment]
@vorpaljs-reforged/vorpal-developers 
1. shall we publish the `master` branch of this repo as `2.0.0-alpha.x` (where `x` starts with 1 and we bump, iterate beta and rc maybe, ultimately ending up with a `2.0.0` stable).
2. shall we rename this repository to match the npm package name?

**Comment by Ore4444** [comment]
> @vorpaljs-reforged/vorpal-developers
> 
>     1. shall we publish the `master` branch of this repo as `2.0.0-alpha.x` (where `x` starts with 1 and we bump, iterate beta and rc maybe, ultimately ending up with a `2.0.0` stable).
> 
>     2. shall we rename this repository to match the npm package name?

i agree with both

**Comment by AdrieanKhisbe** [comment]
M'y :+1: is about thé version schema

About thé package name, I would prefer to keep vorpal as repo.

If we change, that might cause a migration once, and maybe twice if we take back control of vorpal

**Comment by hongaar** [comment]
> If we change, that might cause a migration once, and maybe twice if we take back control of vorpal

Renaming a repo on GitHub is trivial, I think the only thing we need to update is various links in the readme and of course our git remotes.

**Comment by AdrieanKhisbe** [comment]
> > If we change, that might cause a migration once, and maybe twice if we take back control of vorpal
> 
> Renaming a repo on GitHub is trivial, I think the only thing we need to **update is various links in the readme** [*and else*] and of course our git remotes.

That's exactly that point I refer to, github renaming being indeed an effortless operation

**Comment by AdrieanKhisbe** [comment]
Rethining about this, I'm starting to consider first stable published version should be `1.13.0`
(latest vorpal is [`1.12.0`](https://www.npmjs.com/package/vorpal))

**Comment by Ore4444** [comment]
Interesting thought @AdrieanKhisbe . Why?
I'd think because it's a rewrite, we should be able to signal this project's stability by making our first public release a major version bump

**Comment by AdrieanKhisbe** [comment]
It's a rewrite indeed, but it's not suppose to be breaking change (unless we get ride of the session in which case it can only be a 2.0)
And we are stil not sure about the possibility that we get back into vorpal original repository.

**Comment by Ore4444** [comment]
Not supposed to be a breaking change, but with such a big underlying change, i think we can define our semantics in the case of the initial relase

**Comment by hongaar** [comment]
Obligatory link http://sentimentalversioning.org/

BTW I don't have a very strong opinion on this. 😃

**Pull request closed without merging**
