### PR TITLE
chore: upgrade inquirer to ^v7.0.0

### PR DESCRIPTION
**Pull request by hongaar**
Also includes:
- chore: npm audit fix
- style: prettier / eslint

Would be happy to break out these commits into separate PR's and base on a different branch. Just trying out a ton of stuff now and wanted latest changes from @Ore4444 :)

### CODE REVIEW

**Review by Ore4444 — APPROVED** [review]
thanks for making the style consistent
I see the only changes related to inquirer are in ui.ts 
if all tests pass, i approve. the inquirer functionality is pretty well covered in tests

**Review by AdrieanKhisbe — CHANGES_REQUESTED** [review]
There is some problem with the PR:
it should only contains 9e15ff142818dac9ca6eb8e9ea1144e830d3edd6 and b42b443edfaca8812f874200fa12fb971ad156a2

**Comment by AdrieanKhisbe** [comment]
(other than that, that's a ✅ )

**Comment by hongaar** [comment]
> There is some problem with the PR:
> it should only contains [9e15ff1](https://github.com/vorpaljs-reforged/vorpal/commit/9e15ff142818dac9ca6eb8e9ea1144e830d3edd6) and [b42b443](https://github.com/vorpaljs-reforged/vorpal/commit/b42b443edfaca8812f874200fa12fb971ad156a2)

You're right. Accidentally opened this PR for my personal `develop` branch containing all the fixes I needed. Will isolate this commit and open new pr 👍

**Comment by hongaar** [comment]
Closed in favour of #17 and #18.

**Pull request closed without merging**
